Haider

Chapter 4





  



Q5:
-- Bug corrected SELECT shipper_id, companyname FROM Sales.MyShippers WHERE shipper_id IN (SELECT O.shipperid FROM Sales.Orders AS O WHERE O.custid = 43);

-- Cleanup DROP TABLE IF EXISTS Sales.MyShippers;

Chapter 5

Q6:
SELECT S.shipperid, E.empid FROM Sales.Shippers AS S CROSS APPLY HR.Employees AS E;


  

Q7:  
-- Add CHECK OPTION to the View ALTER VIEW Sales.USACusts WITH SCHEMABINDING AS

SELECT custid, companyname, contactname, contacttitle, address, city, region, postalcode, country, phone, fax FROM Sales.Customers WHERE country = N'USA' WITH CHECK OPTION; GO

-- Notice that you can't insert a row through the view /* INSERT INTO Sales.USACusts( companyname, contactname, contacttitle, address, city, region, postalcode, country, phone, fax) VALUES( N'Customer FGHIJ', N'Contact FGHIJ', N'Title FGHIJ', N'Address FGHIJ', N'London', NULL, N'12345', N'UK', N'012-3456789', N'012-3456789'); */ GO

-- Cleanup DELETE FROM Sales.Customers WHERE custid > 91;

DROP VIEW IF EXISTS Sales.USACusts; GO


  

Q8:
-- Instead, use ORDER BY in Outer Query SELECT custid, companyname, region FROM Sales.USACusts ORDER BY region; GO

-- Do not Rely on TOP ALTER VIEW Sales.USACusts AS

SELECT TOP (100) PERCENT custid, companyname, contactname, contacttitle, address, city, region, postalcode, country, phone, fax FROM Sales.Customers WHERE country = N'USA' ORDER BY region; GO






Q9:
-- External column aliasing WITH C(orderyear, custid) AS ( SELECT YEAR(orderdate), custid FROM Sales.Orders ) SELECT orderyear, COUNT(DISTINCT custid) AS numcusts FROM C GROUP BY orderyear; GO


  
Q10:
DECLARE @empid AS INT = 3;

SELECT orderyear, COUNT(DISTINCT custid) AS numcusts FROM (SELECT YEAR(orderdate) AS orderyear, custid FROM Sales.Orders WHERE empid = @empid) AS D GROUP BY orderyear; GO ```

# **PHW 3 -**Â Multiple Queries - Group 2: Haider Abdullah

# Top 5 Queries:

QUERY NUMBER 1

Chapter 4 Excercise 3

Proposition 

--Retrieve order IDs for orders handled by employees whose last name starts with 'D'.
--Tables involved: Sales.Orders and HR.Employees.

Expected Output

orderid
10258
10270
10275
10285
10292
10293
10304
10306
10311
10314
10316
10325
10340
10351
10357
10361
10364
10371
10374
10376
10377
10385
10387
10393
10394
10396
10400
10401
10405
10453
10461
10465
10469
10473
10482
10486
10508
10524
10525
10537
10542
10546
10558
10562
10567
10579
10587
10591
10598
10604
10605
10612
10616
10618
10626
10630
10653
10655
10664
10665
10668
10671
10677
10680
10689
10690
10709
10710
10713
10717
10718
10733
10743
10746
10773
10776
10785
10788
10789
10792
10800
10813
10821
10825
10827
10834
10835
10842
10850
10859
10877
10886
10888
10894
10900
10902
10909
10910
10916
10921
10928
10946
10950
10952
10968
10969
10975
10976
10981
10984
10991
10992
10995
11012
11023
11027
11038
11039
11064
11067
11069
11071
11077
10255
10263
10324
10331
10386
10411
10475
10501
10506
10538
10557
10566
10577
10586
10646
10672
10687
10705
10736
10745
10750
10771
10782
10799
10828
10829
10837
10849
10853
10871
10889
10893
10905
10942
10951
10953
10963
10970
10978
11016
11017
11022
11058

In [ ]:
USE TSQLV4
SELECT orderid FROM Sales.Orders
WHERE empid IN 
(SELECT E.empid FROM HR.Employees AS E WHERE E.lastname LIKE N'D%');


use Northwinds2022TSQLV7
SELECT OrderId FROM Sales.[Order] 
WHERE EmployeeId IN 
(SELECT E.EmployeeId FROM HumanResources.Employee AS E WHERE E.EmployeeLastName LIKE N'D%');

explanation

this query brings the orderid from the sales.Orders table in TSQLV4. it brings the order ids of all employees where last name starts from D and onwards. The 'N' in the query right before D% represents National Language Character set. so it takes in all characters from any language.

In [ ]:
Q2:
-- Orders with maximum order ID for each customer -- Listing 4-1: Correlated Subquery USE TSQLV4;

Proposition
--Retrieve the latest order details for each customer based on the highest orderid.
--Tables involved: Sales.Orders


custid	orderid	orderdate	empid
1	11011	2016-04-09	3
2	10926	2016-03-04	4
3	10856	2016-01-28	3
4	11016	2016-04-10	9
5	10924	2016-03-04	3
6	11058	2016-04-29	9
7	10826	2016-01-12	6
8	10970	2016-03-24	9
9	11076	2016-05-06	4
10	11048	2016-04-24	7
11	11023	2016-04-14	1
12	11054	2016-04-28	8
13	10259	2014-07-18	4
14	11041	2016-04-22	3
15	11042	2016-04-22	2
16	10848	2016-01-23	7
17	11067	2016-05-04	1
18	10890	2016-02-16	7
19	11056	2016-04-28	8
20	11072	2016-05-05	4
21	10725	2015-10-31	4
23	10789	2015-12-22	1
24	11050	2016-04-27	8
25	11012	2016-04-09	1
26	10971	2016-03-24	2
27	11060	2016-04-30	2
28	10963	2016-03-19	9
29	10928	2016-03-05	1
30	11037	2016-04-21	7
31	11049	2016-04-24	3
32	11061	2016-04-30	4
33	10785	2015-12-18	1
34	11052	2016-04-27	3
35	11055	2016-04-28	7
36	10660	2015-09-08	8
37	11063	2016-04-30	3
38	10933	2016-03-06	6
39	11028	2016-04-16	2
40	10973	2016-03-24	6
41	11051	2016-04-27	7
42	10810	2016-01-01	2
43	10545	2015-05-22	8
44	11070	2016-05-05	2
45	10884	2016-02-12	4
46	11071	2016-05-05	1
47	11039	2016-04-21	1
48	11018	2016-04-13	4
49	10950	2016-03-16	1
50	11004	2016-04-07	3
51	10724	2015-10-30	8
52	10945	2016-03-12	4
53	11057	2016-04-29	3
54	10986	2016-03-30	8
55	11034	2016-04-20	8
56	11020	2016-04-14	2
58	11073	2016-05-05	2
59	11053	2016-04-27	2
60	11007	2016-04-08	8
61	10989	2016-03-31	2
62	11068	2016-05-04	8
63	11021	2016-04-14	3
64	11019	2016-04-13	6
65	11077	2016-05-06	1
66	11062	2016-04-30	4
67	11059	2016-04-29	2
68	11075	2016-05-06	8
69	11013	2016-04-09	2
70	11015	2016-04-10	2
71	11064	2016-05-01	1
72	10869	2016-02-04	5
73	11074	2016-05-06	7
74	11043	2016-04-22	5
75	10974	2016-03-25	3
76	11038	2016-04-21	1
77	10992	2016-04-01	1
78	11003	2016-04-06	3
79	10967	2016-03-23	2
80	11069	2016-05-04	1
81	10839	2016-01-19	3
82	10822	2016-01-08	6
83	10994	2016-04-02	2
84	10850	2016-01-23	1
85	10739	2015-11-12	3
86	11046	2016-04-23	8
87	11025	2016-04-15	6
88	10935	2016-03-09	4
89	11066	2016-05-01	7
90	11005	2016-04-07	2
91	11044	2016-04-23	4

In [ ]:
use TSQLV4
SELECT custid, orderid, orderdate, empid 
FROM Sales.Orders AS O1 WHERE 
orderid = (SELECT MAX(O2.orderid) FROM Sales.Orders AS O2 WHERE O2.custid = O1.custid);

USE Northwinds2022TSQLV7;
SELECT CustomerId, OrderId, orderdate, EmployeeId 
FROM Sales.[Order] AS O1 
WHERE OrderId = 
    (SELECT MAX(O2.OrderId) 
     FROM Sales.[Order] AS O2 
     WHERE O2.CustomerId = O1.CustomerId)
ORDER BY CustomerId ASC;

EXPLANATION
in this query we are supposed to find the latest order placed by a customer. selects the most recent order per customer by finding the maximum OrderId for each custid, isolating the latest transaction by comparing OrderId values within customer groups in the Sales.Orders table
here in the code for northwinds i had to add an extra line of sql code to make it the same output. ORDER BY CustomerId ASC; to make it the same output. here in this query


CHAPTER 4 Question 3

Proposition
--Retrieves order details and the ID of the directly preceding order for each entry in the Sales.Orders table.
--Tables involved: Sales.Orders.

Desired output

orderid	orderdate	EmployeeId	CustomerId	prevorderid
10248	2014-07-04	5	85	NULL
10249	2014-07-05	6	79	10248
10250	2014-07-08	4	34	10249
10251	2014-07-08	3	84	10250
10252	2014-07-09	4	76	10251
10253	2014-07-10	3	34	10252
10254	2014-07-11	5	14	10253
10255	2014-07-12	9	68	10254
10256	2014-07-15	3	88	10255
10257	2014-07-16	4	35	10256
10258	2014-07-17	1	20	10257
10259	2014-07-18	4	13	10258
10260	2014-07-19	4	56	10259
10261	2014-07-19	4	61	10260
10262	2014-07-22	8	65	10261
10263	2014-07-23	9	20	10262
10264	2014-07-24	6	24	10263
10265	2014-07-25	2	7	10264
10266	2014-07-26	3	87	10265
10267	2014-07-29	4	25	10266
10268	2014-07-30	8	33	10267
10269	2014-07-31	5	89	10268
10270	2014-08-01	1	87	10269
10271	2014-08-01	6	75	10270
10272	2014-08-02	6	65	10271
10273	2014-08-05	3	63	10272
10274	2014-08-06	6	85	10273
10275	2014-08-07	1	49	10274
10276	2014-08-08	8	80	10275
10277	2014-08-09	2	52	10276
10278	2014-08-12	8	5	10277
10279	2014-08-13	8	44	10278
10280	2014-08-14	2	5	10279
10281	2014-08-14	4	69	10280
10282	2014-08-15	4	69	10281
10283	2014-08-16	3	46	10282
10284	2014-08-19	4	44	10283
10285	2014-08-20	1	63	10284
10286	2014-08-21	8	63	10285
10287	2014-08-22	8	67	10286
10288	2014-08-23	4	66	10287
10289	2014-08-26	7	11	10288
10290	2014-08-27	8	15	10289
10291	2014-08-27	6	61	10290
10292	2014-08-28	1	81	10291
10293	2014-08-29	1	80	10292
10294	2014-08-30	4	65	10293
10295	2014-09-02	2	85	10294
10296	2014-09-03	6	46	10295
10297	2014-09-04	5	7	10296
10298	2014-09-05	6	37	10297
10299	2014-09-06	4	67	10298
10300	2014-09-09	2	49	10299
10301	2014-09-09	8	86	10300
10302	2014-09-10	4	76	10301
10303	2014-09-11	7	30	10302
10304	2014-09-12	1	80	10303
10305	2014-09-13	8	55	10304
10306	2014-09-16	1	69	10305
10307	2014-09-17	2	48	10306
10308	2014-09-18	7	2	10307
10309	2014-09-19	3	37	10308
10310	2014-09-20	8	77	10309
10311	2014-09-20	1	18	10310
10312	2014-09-23	2	86	10311
10313	2014-09-24	2	63	10312
10314	2014-09-25	1	65	10313
10315	2014-09-26	4	38	10314
10316	2014-09-27	1	65	10315
10317	2014-09-30	6	48	10316
10318	2014-10-01	8	38	10317
10319	2014-10-02	7	80	10318
10320	2014-10-03	5	87	10319
10321	2014-10-03	3	38	10320
10322	2014-10-04	7	58	10321
10323	2014-10-07	4	39	10322
10324	2014-10-08	9	71	10323
10325	2014-10-09	1	39	10324
10326	2014-10-10	4	8	10325
10327	2014-10-11	2	24	10326
10328	2014-10-14	4	28	10327
10329	2014-10-15	4	75	10328
10330	2014-10-16	3	46	10329
10331	2014-10-16	9	9	10330
10332	2014-10-17	3	51	10331
10333	2014-10-18	5	87	10332
10334	2014-10-21	8	84	10333
10335	2014-10-22	7	37	10334
10336	2014-10-23	7	60	10335
10337	2014-10-24	4	25	10336
10338	2014-10-25	4	55	10337
10339	2014-10-28	2	51	10338
10340	2014-10-29	1	9	10339
10341	2014-10-29	7	73	10340
10342	2014-10-30	4	25	10341
10343	2014-10-31	4	44	10342
10344	2014-11-01	4	89	10343
10345	2014-11-04	2	63	10344
10346	2014-11-05	3	65	10345
10347	2014-11-06	4	21	10346
10348	2014-11-07	4	86	10347
10349	2014-11-08	7	75	10348
10350	2014-11-11	6	41	10349
10351	2014-11-11	1	20	10350
10352	2014-11-12	3	28	10351
10353	2014-11-13	7	59	10352
10354	2014-11-14	8	58	10353
10355	2014-11-15	6	4	10354
10356	2014-11-18	6	86	10355
10357	2014-11-19	1	46	10356
10358	2014-11-20	5	41	10357
10359	2014-11-21	5	72	10358
10360	2014-11-22	4	7	10359
10361	2014-11-22	1	63	10360
10362	2014-11-25	3	9	10361
10363	2014-11-26	4	17	10362
10364	2014-11-26	1	19	10363
10365	2014-11-27	3	3	10364
10366	2014-11-28	8	29	10365
10367	2014-11-28	7	83	10366
10368	2014-11-29	2	20	10367
10369	2014-12-02	8	75	10368
10370	2014-12-03	6	14	10369
10371	2014-12-03	1	41	10370
10372	2014-12-04	5	62	10371
10373	2014-12-05	4	37	10372
10374	2014-12-05	1	91	10373
10375	2014-12-06	3	36	10374
10376	2014-12-09	1	51	10375
10377	2014-12-09	1	72	10376
10378	2014-12-10	5	24	10377
10379	2014-12-11	2	61	10378
10380	2014-12-12	8	37	10379
10381	2014-12-12	3	46	10380
10382	2014-12-13	4	20	10381
10383	2014-12-16	8	4	10382
10384	2014-12-16	3	5	10383
10385	2014-12-17	1	75	10384
10386	2014-12-18	9	21	10385
10387	2014-12-18	1	70	10386
10388	2014-12-19	2	72	10387
10389	2014-12-20	4	10	10388
10390	2014-12-23	6	20	10389
10391	2014-12-23	3	17	10390
10392	2014-12-24	2	59	10391
10393	2014-12-25	1	71	10392
10394	2014-12-25	1	36	10393
10395	2014-12-26	6	35	10394
10396	2014-12-27	1	25	10395
10397	2014-12-27	5	60	10396
10398	2014-12-30	2	71	10397
10399	2014-12-31	8	83	10398
10400	2015-01-01	1	19	10399
10401	2015-01-01	1	65	10400
10402	2015-01-02	8	20	10401
10403	2015-01-03	4	20	10402
10404	2015-01-03	2	49	10403
10405	2015-01-06	1	47	10404
10406	2015-01-07	7	62	10405
10407	2015-01-07	2	56	10406
10408	2015-01-08	8	23	10407
10409	2015-01-09	3	54	10408
10410	2015-01-10	3	10	10409
10411	2015-01-10	9	10	10410
10412	2015-01-13	8	87	10411
10413	2015-01-14	3	41	10412
10414	2015-01-14	2	21	10413
10415	2015-01-15	3	36	10414
10416	2015-01-16	8	87	10415
10417	2015-01-16	4	73	10416
10418	2015-01-17	4	63	10417
10419	2015-01-20	4	68	10418
10420	2015-01-21	3	88	10419
10421	2015-01-21	8	61	10420
10422	2015-01-22	2	27	10421
10423	2015-01-23	6	31	10422
10424	2015-01-23	7	51	10423
10425	2015-01-24	6	41	10424
10426	2015-01-27	4	29	10425
10427	2015-01-27	4	59	10426
10428	2015-01-28	7	66	10427
10429	2015-01-29	3	37	10428
10430	2015-01-30	4	20	10429
10431	2015-01-30	4	10	10430
10432	2015-01-31	3	75	10431
10433	2015-02-03	3	60	10432
10434	2015-02-03	3	24	10433
10435	2015-02-04	8	16	10434
10436	2015-02-05	3	7	10435
10437	2015-02-05	8	87	10436
10438	2015-02-06	3	79	10437
10439	2015-02-07	6	51	10438
10440	2015-02-10	4	71	10439
10441	2015-02-10	3	55	10440
10442	2015-02-11	3	20	10441
10443	2015-02-12	8	66	10442
10444	2015-02-12	3	5	10443
10445	2015-02-13	3	5	10444
10446	2015-02-14	6	79	10445
10447	2015-02-14	4	67	10446
10448	2015-02-17	4	64	10447
10449	2015-02-18	3	7	10448
10450	2015-02-19	8	84	10449
10451	2015-02-19	4	63	10450
10452	2015-02-20	8	71	10451
10453	2015-02-21	1	4	10452
10454	2015-02-21	4	41	10453
10455	2015-02-24	8	87	10454
10456	2015-02-25	8	39	10455
10457	2015-02-25	2	39	10456
10458	2015-02-26	7	76	10457
10459	2015-02-27	4	84	10458
10460	2015-02-28	8	24	10459
10461	2015-02-28	1	46	10460
10462	2015-03-03	2	16	10461
10463	2015-03-04	5	76	10462
10464	2015-03-04	4	28	10463
10465	2015-03-05	1	83	10464
10466	2015-03-06	4	15	10465
10467	2015-03-06	8	49	10466
10468	2015-03-07	3	39	10467
10469	2015-03-10	1	89	10468
10470	2015-03-11	4	9	10469
10471	2015-03-11	2	11	10470
10472	2015-03-12	8	72	10471
10473	2015-03-13	1	38	10472
10474	2015-03-13	5	58	10473
10475	2015-03-14	9	76	10474
10476	2015-03-17	8	35	10475
10477	2015-03-17	5	60	10476
10478	2015-03-18	2	84	10477
10479	2015-03-19	3	65	10478
10480	2015-03-20	6	23	10479
10481	2015-03-20	8	67	10480
10482	2015-03-21	1	43	10481
10483	2015-03-24	7	89	10482
10484	2015-03-24	3	11	10483
10485	2015-03-25	4	47	10484
10486	2015-03-26	1	35	10485
10487	2015-03-26	2	62	10486
10488	2015-03-27	8	25	10487
10489	2015-03-28	6	59	10488
10490	2015-03-31	7	35	10489
10491	2015-03-31	8	28	10490
10492	2015-04-01	3	10	10491
10493	2015-04-02	4	41	10492
10494	2015-04-02	4	15	10493
10495	2015-04-03	3	42	10494
10496	2015-04-04	7	81	10495
10497	2015-04-04	7	44	10496
10498	2015-04-07	8	35	10497
10499	2015-04-08	4	46	10498
10500	2015-04-09	6	41	10499
10501	2015-04-09	9	6	10500
10502	2015-04-10	2	58	10501
10503	2015-04-11	6	37	10502
10504	2015-04-11	4	89	10503
10505	2015-04-14	3	51	10504
10506	2015-04-15	9	39	10505
10507	2015-04-15	7	3	10506
10508	2015-04-16	1	56	10507
10509	2015-04-17	4	6	10508
10510	2015-04-18	6	71	10509
10511	2015-04-18	4	9	10510
10512	2015-04-21	7	21	10511
10513	2015-04-22	7	86	10512
10514	2015-04-22	3	20	10513
10515	2015-04-23	2	63	10514
10516	2015-04-24	2	37	10515
10517	2015-04-24	3	53	10516
10518	2015-04-25	4	80	10517
10519	2015-04-28	6	14	10518
10520	2015-04-29	7	70	10519
10521	2015-04-29	8	12	10520
10522	2015-04-30	4	44	10521
10523	2015-05-01	7	72	10522
10524	2015-05-01	1	5	10523
10525	2015-05-02	1	9	10524
10526	2015-05-05	4	87	10525
10527	2015-05-05	7	63	10526
10528	2015-05-06	6	32	10527
10529	2015-05-07	5	50	10528
10530	2015-05-08	3	59	10529
10531	2015-05-08	7	54	10530
10532	2015-05-09	7	19	10531
10533	2015-05-12	8	24	10532
10534	2015-05-12	8	44	10533
10535	2015-05-13	4	3	10534
10536	2015-05-14	3	44	10535
10537	2015-05-14	1	68	10536
10538	2015-05-15	9	11	10537
10539	2015-05-16	6	11	10538
10540	2015-05-19	3	63	10539
10541	2015-05-19	2	34	10540
10542	2015-05-20	1	39	10541
10543	2015-05-21	8	46	10542
10544	2015-05-21	4	48	10543
10545	2015-05-22	8	43	10544
10546	2015-05-23	1	84	10545
10547	2015-05-23	3	72	10546
10548	2015-05-26	3	79	10547
10549	2015-05-27	5	63	10548
10550	2015-05-28	7	30	10549
10551	2015-05-28	4	28	10550
10552	2015-05-29	2	35	10551
10553	2015-05-30	2	87	10552
10554	2015-05-30	4	56	10553
10555	2015-06-02	6	71	10554
10556	2015-06-03	2	73	10555
10557	2015-06-03	9	44	10556
10558	2015-06-04	1	4	10557
10559	2015-06-05	6	7	10558
10560	2015-06-06	8	25	10559
10561	2015-06-06	2	24	10560
10562	2015-06-09	1	66	10561
10563	2015-06-10	2	67	10562
10564	2015-06-10	4	65	10563
10565	2015-06-11	8	51	10564
10566	2015-06-12	9	7	10565
10567	2015-06-12	1	37	10566
10568	2015-06-13	3	29	10567
10569	2015-06-16	5	65	10568
10570	2015-06-17	3	51	10569
10571	2015-06-17	8	20	10570
10572	2015-06-18	3	5	10571
10573	2015-06-19	7	3	10572
10574	2015-06-19	4	82	10573
10575	2015-06-20	5	52	10574
10576	2015-06-23	3	80	10575
10577	2015-06-23	9	82	10576
10578	2015-06-24	4	11	10577
10579	2015-06-25	1	45	10578
10580	2015-06-26	4	56	10579
10581	2015-06-26	3	21	10580
10582	2015-06-27	3	6	10581
10583	2015-06-30	2	87	10582
10584	2015-06-30	4	7	10583
10585	2015-07-01	7	88	10584
10586	2015-07-02	9	66	10585
10587	2015-07-02	1	61	10586
10588	2015-07-03	2	63	10587
10589	2015-07-04	8	32	10588
10590	2015-07-07	4	51	10589
10591	2015-07-07	1	83	10590
10592	2015-07-08	3	44	10591
10593	2015-07-09	7	44	10592
10594	2015-07-09	3	55	10593
10595	2015-07-10	2	20	10594
10596	2015-07-11	8	89	10595
10597	2015-07-11	7	59	10596
10598	2015-07-14	1	65	10597
10599	2015-07-15	6	11	10598
10600	2015-07-16	4	36	10599
10601	2015-07-16	7	35	10600
10602	2015-07-17	8	83	10601
10603	2015-07-18	8	71	10602
10604	2015-07-18	1	28	10603
10605	2015-07-21	1	51	10604
10606	2015-07-22	4	81	10605
10607	2015-07-22	5	71	10606
10608	2015-07-23	4	79	10607
10609	2015-07-24	7	18	10608
10610	2015-07-25	8	41	10609
10611	2015-07-25	6	91	10610
10612	2015-07-28	1	71	10611
10613	2015-07-29	4	35	10612
10614	2015-07-29	8	6	10613
10615	2015-07-30	2	90	10614
10616	2015-07-31	1	32	10615
10617	2015-07-31	4	32	10616
10618	2015-08-01	1	51	10617
10619	2015-08-04	3	51	10618
10620	2015-08-05	2	42	10619
10621	2015-08-05	4	38	10620
10622	2015-08-06	4	67	10621
10623	2015-08-07	8	25	10622
10624	2015-08-07	4	78	10623
10625	2015-08-08	3	2	10624
10626	2015-08-11	1	5	10625
10627	2015-08-11	8	71	10626
10628	2015-08-12	4	7	10627
10629	2015-08-12	4	30	10628
10630	2015-08-13	1	39	10629
10631	2015-08-14	8	41	10630
10632	2015-08-14	8	86	10631
10633	2015-08-15	7	20	10632
10634	2015-08-15	4	23	10633
10635	2015-08-18	8	49	10634
10636	2015-08-19	4	87	10635
10637	2015-08-19	6	62	10636
10638	2015-08-20	3	47	10637
10639	2015-08-20	7	70	10638
10640	2015-08-21	4	86	10639
10641	2015-08-22	4	35	10640
10642	2015-08-22	7	73	10641
10643	2015-08-25	6	1	10642
10644	2015-08-25	3	88	10643
10645	2015-08-26	4	34	10644
10646	2015-08-27	9	37	10645
10647	2015-08-27	4	61	10646
10648	2015-08-28	5	67	10647
10649	2015-08-28	5	50	10648
10650	2015-08-29	5	21	10649
10651	2015-09-01	8	86	10650
10652	2015-09-01	4	31	10651
10653	2015-09-02	1	25	10652
10654	2015-09-02	5	5	10653
10655	2015-09-03	1	66	10654
10656	2015-09-04	6	32	10655
10657	2015-09-04	2	71	10656
10658	2015-09-05	4	63	10657
10659	2015-09-05	7	62	10658
10660	2015-09-08	8	36	10659
10661	2015-09-09	7	37	10660
10662	2015-09-09	3	48	10661
10663	2015-09-10	2	9	10662
10664	2015-09-10	1	28	10663
10665	2015-09-11	1	48	10664
10666	2015-09-12	7	68	10665
10667	2015-09-12	7	20	10666
10668	2015-09-15	1	86	10667
10669	2015-09-15	2	73	10668
10670	2015-09-16	4	25	10669
10671	2015-09-17	1	26	10670
10672	2015-09-17	9	5	10671
10673	2015-09-18	2	90	10672
10674	2015-09-18	4	38	10673
10675	2015-09-19	5	25	10674
10676	2015-09-22	2	80	10675
10677	2015-09-22	1	3	10676
10678	2015-09-23	7	71	10677
10679	2015-09-23	8	7	10678
10680	2015-09-24	1	55	10679
10681	2015-09-25	3	32	10680
10682	2015-09-25	3	3	10681
10683	2015-09-26	2	18	10682
10684	2015-09-26	3	56	10683
10685	2015-09-29	4	31	10684
10686	2015-09-30	2	59	10685
10687	2015-09-30	9	37	10686
10688	2015-10-01	4	83	10687
10689	2015-10-01	1	5	10688
10690	2015-10-02	1	34	10689
10691	2015-10-03	2	63	10690
10692	2015-10-03	4	1	10691
10693	2015-10-06	3	89	10692
10694	2015-10-06	8	63	10693
10695	2015-10-07	7	90	10694
10696	2015-10-08	8	89	10695
10697	2015-10-08	3	47	10696
10698	2015-10-09	4	20	10697
10699	2015-10-09	3	52	10698
10700	2015-10-10	3	71	10699
10701	2015-10-13	6	37	10700
10702	2015-10-13	4	1	10701
10703	2015-10-14	6	24	10702
10704	2015-10-14	6	62	10703
10705	2015-10-15	9	35	10704
10706	2015-10-16	8	55	10705
10707	2015-10-16	4	4	10706
10708	2015-10-17	6	77	10707
10709	2015-10-17	1	31	10708
10710	2015-10-20	1	27	10709
10711	2015-10-21	5	71	10710
10712	2015-10-21	3	37	10711
10713	2015-10-22	1	71	10712
10714	2015-10-22	5	71	10713
10715	2015-10-23	3	9	10714
10716	2015-10-24	4	64	10715
10717	2015-10-24	1	25	10716
10718	2015-10-27	1	39	10717
10719	2015-10-27	8	45	10718
10720	2015-10-28	8	61	10719
10721	2015-10-29	5	63	10720
10722	2015-10-29	8	71	10721
10723	2015-10-30	3	89	10722
10724	2015-10-30	8	51	10723
10725	2015-10-31	4	21	10724
10726	2015-11-03	4	19	10725
10727	2015-11-03	2	66	10726
10728	2015-11-04	4	62	10727
10729	2015-11-04	8	47	10728
10730	2015-11-05	5	9	10729
10731	2015-11-06	7	14	10730
10732	2015-11-06	3	9	10731
10733	2015-11-07	1	5	10732
10734	2015-11-07	2	31	10733
10735	2015-11-10	6	45	10734
10736	2015-11-11	9	37	10735
10737	2015-11-11	2	85	10736
10738	2015-11-12	2	74	10737
10739	2015-11-12	3	85	10738
10740	2015-11-13	4	89	10739
10741	2015-11-14	4	4	10740
10742	2015-11-14	3	10	10741
10743	2015-11-17	1	4	10742
10744	2015-11-17	6	83	10743
10745	2015-11-18	9	63	10744
10746	2015-11-19	1	14	10745
10747	2015-11-19	6	59	10746
10748	2015-11-20	3	71	10747
10749	2015-11-20	4	38	10748
10750	2015-11-21	9	87	10749
10751	2015-11-24	3	68	10750
10752	2015-11-24	2	53	10751
10753	2015-11-25	3	27	10752
10754	2015-11-25	6	49	10753
10755	2015-11-26	4	9	10754
10756	2015-11-27	8	75	10755
10757	2015-11-27	6	71	10756
10758	2015-11-28	3	68	10757
10759	2015-11-28	3	2	10758
10760	2015-12-01	4	50	10759
10761	2015-12-02	5	65	10760
10762	2015-12-02	3	24	10761
10763	2015-12-03	3	23	10762
10764	2015-12-03	6	20	10763
10765	2015-12-04	3	63	10764
10766	2015-12-05	4	56	10765
10767	2015-12-05	4	76	10766
10768	2015-12-08	3	4	10767
10769	2015-12-08	3	83	10768
10770	2015-12-09	8	34	10769
10771	2015-12-10	9	20	10770
10772	2015-12-10	3	44	10771
10773	2015-12-11	1	20	10772
10774	2015-12-11	4	24	10773
10775	2015-12-12	7	78	10774
10776	2015-12-15	1	20	10775
10777	2015-12-15	7	31	10776
10778	2015-12-16	3	5	10777
10779	2015-12-16	3	52	10778
10780	2015-12-16	2	46	10779
10781	2015-12-17	2	87	10780
10782	2015-12-17	9	12	10781
10783	2015-12-18	4	34	10782
10784	2015-12-18	4	49	10783
10785	2015-12-18	1	33	10784
10786	2015-12-19	8	62	10785
10787	2015-12-19	2	41	10786
10788	2015-12-22	1	63	10787
10789	2015-12-22	1	23	10788
10790	2015-12-22	6	31	10789
10791	2015-12-23	6	25	10790
10792	2015-12-23	1	91	10791
10793	2015-12-24	3	4	10792
10794	2015-12-24	6	61	10793
10795	2015-12-24	8	20	10794
10796	2015-12-25	3	35	10795
10797	2015-12-25	7	17	10796
10798	2015-12-26	2	38	10797
10799	2015-12-26	9	39	10798
10800	2015-12-26	1	72	10799
10801	2015-12-29	4	8	10800
10802	2015-12-29	4	73	10801
10803	2015-12-30	4	88	10802
10804	2015-12-30	6	72	10803
10805	2015-12-30	2	77	10804
10806	2015-12-31	3	84	10805
10807	2015-12-31	4	27	10806
10808	2016-01-01	2	55	10807
10809	2016-01-01	7	88	10808
10810	2016-01-01	2	42	10809
10811	2016-01-02	8	47	10810
10812	2016-01-02	5	66	10811
10813	2016-01-05	1	67	10812
10814	2016-01-05	3	84	10813
10815	2016-01-05	2	71	10814
10816	2016-01-06	4	32	10815
10817	2016-01-06	3	39	10816
10818	2016-01-07	7	49	10817
10819	2016-01-07	2	12	10818
10820	2016-01-07	3	65	10819
10821	2016-01-08	1	75	10820
10822	2016-01-08	6	82	10821
10823	2016-01-09	5	46	10822
10824	2016-01-09	8	24	10823
10825	2016-01-09	1	17	10824
10826	2016-01-12	6	7	10825
10827	2016-01-12	1	9	10826
10828	2016-01-13	9	64	10827
10829	2016-01-13	9	38	10828
10830	2016-01-13	4	81	10829
10831	2016-01-14	3	70	10830
10832	2016-01-14	2	41	10831
10833	2016-01-15	6	56	10832
10834	2016-01-15	1	81	10833
10835	2016-01-15	1	1	10834
10836	2016-01-16	7	20	10835
10837	2016-01-16	9	5	10836
10838	2016-01-19	3	47	10837
10839	2016-01-19	3	81	10838
10840	2016-01-19	4	47	10839
10841	2016-01-20	5	76	10840
10842	2016-01-20	1	80	10841
10843	2016-01-21	4	84	10842
10844	2016-01-21	8	59	10843
10845	2016-01-21	8	63	10844
10846	2016-01-22	2	76	10845
10847	2016-01-22	4	71	10846
10848	2016-01-23	7	16	10847
10849	2016-01-23	9	39	10848
10850	2016-01-23	1	84	10849
10851	2016-01-26	5	67	10850
10852	2016-01-26	8	65	10851
10853	2016-01-27	9	6	10852
10854	2016-01-27	3	20	10853
10855	2016-01-27	3	55	10854
10856	2016-01-28	3	3	10855
10857	2016-01-28	8	5	10856
10858	2016-01-29	2	40	10857
10859	2016-01-29	1	25	10858
10860	2016-01-29	3	26	10859
10861	2016-01-30	4	89	10860
10862	2016-01-30	8	44	10861
10863	2016-02-02	4	35	10862
10864	2016-02-02	4	4	10863
10865	2016-02-02	2	63	10864
10866	2016-02-03	5	5	10865
10867	2016-02-03	6	48	10866
10868	2016-02-04	7	62	10867
10869	2016-02-04	5	72	10868
10870	2016-02-04	5	91	10869
10871	2016-02-05	9	9	10870
10872	2016-02-05	5	30	10871
10873	2016-02-06	4	90	10872
10874	2016-02-06	5	30	10873
10875	2016-02-06	4	5	10874
10876	2016-02-09	7	9	10875
10877	2016-02-09	1	67	10876
10878	2016-02-10	4	63	10877
10879	2016-02-10	3	90	10878
10880	2016-02-10	7	24	10879
10881	2016-02-11	4	12	10880
10882	2016-02-11	4	71	10881
10883	2016-02-12	8	48	10882
10884	2016-02-12	4	45	10883
10885	2016-02-12	6	76	10884
10886	2016-02-13	1	34	10885
10887	2016-02-13	8	29	10886
10888	2016-02-16	1	30	10887
10889	2016-02-16	9	65	10888
10890	2016-02-16	7	18	10889
10891	2016-02-17	7	44	10890
10892	2016-02-17	4	50	10891
10893	2016-02-18	9	39	10892
10894	2016-02-18	1	71	10893
10895	2016-02-18	3	20	10894
10896	2016-02-19	7	50	10895
10897	2016-02-19	3	37	10896
10898	2016-02-20	4	54	10897
10899	2016-02-20	5	46	10898
10900	2016-02-20	1	88	10899
10901	2016-02-23	4	35	10900
10902	2016-02-23	1	24	10901
10903	2016-02-24	3	34	10902
10904	2016-02-24	3	89	10903
10905	2016-02-24	9	88	10904
10906	2016-02-25	4	91	10905
10907	2016-02-25	6	74	10906
10908	2016-02-26	4	66	10907
10909	2016-02-26	1	70	10908
10910	2016-02-26	1	90	10909
10911	2016-02-26	3	30	10910
10912	2016-02-26	2	37	10911
10913	2016-02-26	4	62	10912
10914	2016-02-27	6	62	10913
10915	2016-02-27	2	80	10914
10916	2016-02-27	1	64	10915
10917	2016-03-02	4	69	10916
10918	2016-03-02	3	10	10917
10919	2016-03-02	2	47	10918
10920	2016-03-03	4	4	10919
10921	2016-03-03	1	83	10920
10922	2016-03-03	5	34	10921
10923	2016-03-03	7	41	10922
10924	2016-03-04	3	5	10923
10925	2016-03-04	3	34	10924
10926	2016-03-04	4	2	10925
10927	2016-03-05	4	40	10926
10928	2016-03-05	1	29	10927
10929	2016-03-05	6	25	10928
10930	2016-03-06	4	76	10929
10931	2016-03-06	4	68	10930
10932	2016-03-06	8	9	10931
10933	2016-03-06	6	38	10932
10934	2016-03-09	3	44	10933
10935	2016-03-09	4	88	10934
10936	2016-03-09	3	32	10935
10937	2016-03-10	7	12	10936
10938	2016-03-10	3	63	10937
10939	2016-03-10	2	49	10938
10940	2016-03-11	8	9	10939
10941	2016-03-11	7	71	10940
10942	2016-03-11	9	66	10941
10943	2016-03-11	4	11	10942
10944	2016-03-12	6	10	10943
10945	2016-03-12	4	52	10944
10946	2016-03-12	1	83	10945
10947	2016-03-13	3	11	10946
10948	2016-03-13	3	30	10947
10949	2016-03-13	2	10	10948
10950	2016-03-16	1	49	10949
10951	2016-03-16	9	68	10950
10952	2016-03-16	1	1	10951
10953	2016-03-16	9	4	10952
10954	2016-03-17	5	47	10953
10955	2016-03-17	8	24	10954
10956	2016-03-17	6	6	10955
10957	2016-03-18	8	35	10956
10958	2016-03-18	7	54	10957
10959	2016-03-18	6	31	10958
10960	2016-03-19	3	35	10959
10961	2016-03-19	8	62	10960
10962	2016-03-19	8	63	10961
10963	2016-03-19	9	28	10962
10964	2016-03-20	3	74	10963
10965	2016-03-20	6	55	10964
10966	2016-03-20	4	14	10965
10967	2016-03-23	2	79	10966
10968	2016-03-23	1	20	10967
10969	2016-03-23	1	15	10968
10970	2016-03-24	9	8	10969
10971	2016-03-24	2	26	10970
10972	2016-03-24	4	40	10971
10973	2016-03-24	6	40	10972
10974	2016-03-25	3	75	10973
10975	2016-03-25	1	10	10974
10976	2016-03-25	1	35	10975
10977	2016-03-26	8	24	10976
10978	2016-03-26	9	50	10977
10979	2016-03-26	8	20	10978
10980	2016-03-27	4	24	10979
10981	2016-03-27	1	34	10980
10982	2016-03-27	2	10	10981
10983	2016-03-27	2	71	10982
10984	2016-03-30	1	71	10983
10985	2016-03-30	2	37	10984
10986	2016-03-30	8	54	10985
10987	2016-03-31	8	19	10986
10988	2016-03-31	3	65	10987
10989	2016-03-31	2	61	10988
10990	2016-04-01	2	20	10989
10991	2016-04-01	1	63	10990
10992	2016-04-01	1	77	10991
10993	2016-04-01	7	24	10992
10994	2016-04-02	2	83	10993
10995	2016-04-02	1	58	10994
10996	2016-04-02	4	63	10995
10997	2016-04-03	8	46	10996
10998	2016-04-03	8	91	10997
10999	2016-04-03	6	56	10998
11000	2016-04-06	2	65	10999
11001	2016-04-06	2	24	11000
11002	2016-04-06	4	71	11001
11003	2016-04-06	3	78	11002
11004	2016-04-07	3	50	11003
11005	2016-04-07	2	90	11004
11006	2016-04-07	3	32	11005
11007	2016-04-08	8	60	11006
11008	2016-04-08	7	20	11007
11009	2016-04-08	2	30	11008
11010	2016-04-09	2	66	11009
11011	2016-04-09	3	1	11010
11012	2016-04-09	1	25	11011
11013	2016-04-09	2	69	11012
11014	2016-04-10	2	47	11013
11015	2016-04-10	2	70	11014
11016	2016-04-10	9	4	11015
11017	2016-04-13	9	20	11016
11018	2016-04-13	4	48	11017
11019	2016-04-13	6	64	11018
11020	2016-04-14	2	56	11019
11021	2016-04-14	3	63	11020
11022	2016-04-14	9	34	11021
11023	2016-04-14	1	11	11022
11024	2016-04-15	4	19	11023
11025	2016-04-15	6	87	11024
11026	2016-04-15	4	27	11025
11027	2016-04-16	1	10	11026
11028	2016-04-16	2	39	11027
11029	2016-04-16	4	14	11028
11030	2016-04-17	7	71	11029
11031	2016-04-17	6	71	11030
11032	2016-04-17	2	89	11031
11033	2016-04-17	7	68	11032
11034	2016-04-20	8	55	11033
11035	2016-04-20	2	76	11034
11036	2016-04-20	8	17	11035
11037	2016-04-21	7	30	11036
11038	2016-04-21	1	76	11037
11039	2016-04-21	1	47	11038
11040	2016-04-22	4	32	11039
11041	2016-04-22	3	14	11040
11042	2016-04-22	2	15	11041
11043	2016-04-22	5	74	11042
11044	2016-04-23	4	91	11043
11045	2016-04-23	6	10	11044
11046	2016-04-23	8	86	11045
11047	2016-04-24	7	19	11046
11048	2016-04-24	7	10	11047
11049	2016-04-24	3	31	11048
11050	2016-04-27	8	24	11049
11051	2016-04-27	7	41	11050
11052	2016-04-27	3	34	11051
11053	2016-04-27	2	59	11052
11054	2016-04-28	8	12	11053
11055	2016-04-28	7	35	11054
11056	2016-04-28	8	19	11055
11057	2016-04-29	3	53	11056
11058	2016-04-29	9	6	11057
11059	2016-04-29	2	67	11058
11060	2016-04-30	2	27	11059
11061	2016-04-30	4	32	11060
11062	2016-04-30	4	66	11061
11063	2016-04-30	3	37	11062
11064	2016-05-01	1	71	11063
11065	2016-05-01	8	46	11064
11066	2016-05-01	7	89	11065
11067	2016-05-04	1	17	11066
11068	2016-05-04	8	62	11067
11069	2016-05-04	1	80	11068
11070	2016-05-05	2	44	11069
11071	2016-05-05	1	46	11070
11072	2016-05-05	4	20	11071
11073	2016-05-05	2	58	11072
11074	2016-05-06	7	73	11073
11075	2016-05-06	8	68	11074
11076	2016-05-06	4	9	11075
11077	2016-05-06	1	65	11076

In [ ]:
Use TSQLV4
SELECT orderid, orderdate, empid, custid, (SELECT MAX(O2.orderid)
FROM Sales.Orders AS O2 
WHERE O2.orderid < O1.orderid) AS prevorderid FROM Sales.Orders AS O1;

Use Northwinds2022TSQLV7
SELECT orderid, orderdate, EmployeeId, CustomerId, (SELECT MAX(O2.orderid)
FROM Sales.[Order] AS O2 
WHERE O2.orderid < O1.orderid) AS prevorderid FROM Sales.[Order] AS O1;


EXPLANATION
this query uses a subquery to make a sort of a self join on the Sales.Order table. It compares each OrderId againt all the others to find the nearest 'lower; orderid. THis is done by the conditin in WHERE line.

Q4:
-- The safe way using aliases, bug identified SELECT shipper_id, companyname FROM Sales.MyShippers WHERE shipper_id IN (SELECT O.shipper_id FROM Sales.Orders AS O WHERE O.custid = 43); GO


Proposition
--Retrieves shipper_id and companyname for shippers involved in orders made by customer ID 43.
--Queries involve Sales.Shippers and Sales.Orders tables within the TSQLV4 database.

Expected Output

shipperid	companyname
2	Shipper ETYNR
3	Shipper ZHISN

In [ ]:
--use TSQLV4
--SELECT shipper_id, companyname FROM Sales.MyShippers 
--WHERE shipper_id IN (SELECT O.shipper_id FROM Sales.Orders AS O WHERE O.custid = 43);


use Northwinds2022TSQLV7
SELECT shipperid, ShipperCompanyName FROM Sales.Shipper 
WHERE shipperid IN (SELECT O.shipperid FROM Sales.[Order] AS O WHERE O.CustomerId = 43);


EXPLANATION
the shipper_id and companyname from the Sales.Shippers table for those shippers who have shipped orders for customer ID 43. It accomplishes this by using a subquery within the WHERE clause to identify shipper_ids in the Sales.Orders. The result is a filtered list from the Sales.MyShippers table, showing only the shippers who have actually shipped orders for this particular customer

QUESTION 5

Proposition
--Fetches shipperid and ShipperCompanyName for shippers that handled orders from customer ID 43
--Involves a subquery to filter relevant shipperids from the Sales.[Order] table.

Expected Output

shipperid	ShipperCompanyName
2	Shipper ETYNR
3	Shipper ZHISN

In [ ]:
--use TSQLV4
--SELECT shipperid, companyname 
--FROM Sales.Shippers 
--WHERE shipperid IN (SELECT O.shipperid FROM Sales.Orders AS O WHERE O.custid = 43);


use Northwinds2022TSQLV7
SELECT shipperid, ShipperCompanyName 
FROM Sales.Shipper 
WHERE shipperid IN (SELECT O.shipperid FROM Sales.[Order] AS O WHERE O.CustomerId = 43);

EXPLANATION
this query had a table deletion line which i did not add above. the command was to check if the Sales.MyShippers table exists, if it does, delete it. Turns out it didnt exist. But this query is the same as the previous one. it retrieves the comapny name tied with a specific customer id which is 43.

CHAPTER 5 QUESTION 6

Proposition
--Retrieve every combination of shipperid from Sales.Shippers and empid from HR.Employees using a CROSS APPLY.
--Operates within the TSQLV4 database, involving tables Sales.Shippers and HR.Employees


Expected Output 
shipperid	empid
1	1
1	2
1	3
1	4
1	5
1	6
1	7
1	8
1	9
2	1
2	2
2	3
2	4
2	5
2	6
2	7
2	8
2	9
3	1
3	2
3	3
3	4
3	5
3	6
3	7
3	8
3	9

In [ ]:
--USE TSQLV4
--SELECT S.shipperid, E.empid 
--FROM Sales.Shippers AS S CROSS APPLY HR.Employees AS E;

USE Northwinds2022TSQLV7
SELECT S.shipperid, E.EmployeeId 
FROM Sales.Shipper AS S CROSS APPLY HumanResources.Employee AS E;


EXPLANATION
here we use a cross apply to combine each row from sales.shipper to every row in HR.Employee table it showcases a dataset where each shipper is associated with all employees. to show each shipper for each employee.

Chapter 5 Question 7

Proposition
--
--

Expected output
shipperid	empid
1	1
1	2
1	3
1	4
1	5
1	6
1	7
1	8
1	9
2	1
2	2
2	3
2	4
2	5
2	6
2	7
2	8
2	9
3	1
3	2
3	3
3	4
3	5
3	6
3	7
3	8
3	9

In [ ]:
--Use TSQLV4
--SELECT S.shipperid, E.empid 
--FROM Sales.Shippers AS S CROSS APPLY HR.Employees AS E;

Use Northwinds2022TSQLV7
SELECT S.shipperid, E.EmployeeId 
FROM Sales.Shipper AS S CROSS APPLY HumanResources.Employee AS E;

 EXPLANATION

Chapter 5 question 7
-- Add CHECK OPTION to the View ALTER VIEW Sales.USACusts WITH SCHEMABINDING AS

SELECT custid, companyname, contactname, contacttitle, address, city, region, postalcode, country, phone, fax FROM Sales.Customers WHERE country = N'USA' WITH CHECK OPTION; GO

-- Notice that you can't insert a row through the view /* INSERT INTO Sales.USACusts( companyname, contactname, contacttitle, address, city, region, postalcode, country, phone, fax) VALUES( N'Customer FGHIJ', N'Contact FGHIJ', N'Title FGHIJ', N'Address FGHIJ', N'London', NULL, N'12345', N'UK', N'012-3456789', N'012-3456789'); */ GO

-- Cleanup DELETE FROM Sales.Customers WHERE custid > 91;

DROP VIEW IF EXISTS Sales.USACusts; GO




Proposition 
--retrieve all details for customers located in the USA from the Sales.Customers table, ensuring any modifications through this dataset respect the same country condition


Expected Output
custid	companyname	contactname	    contacttitle      	address	city	region	postalcode	country	phone	fax
32	Customer YSIQX	Krishnan, Venky	Marketing Manager	6789 Baker Blvd.	Eugene	OR	10070	USA	(503) 555-0122	NULL
36	Customer LVJSO	Smith, Denise	Sales Representative	City Center Plaza 2345 Main St.	Elgin	OR	10103	USA	(503) 555-0126	(503) 555-0135
43	Customer UISOJ	Wu, Qiong	    Marketing Manager	8901 Orchestra Terrace	Walla Walla	WA	10069	USA	(509) 555-0119	(509) 555-0130
45	Customer QXPPT	Wright, David	Owner	1234 Polk St. Suite 5	San Francisco	CA	10062	USA	(415) 555-0118	NULL
48	Customer DVFMB	Szymczak,    	Sales Manager	9012 Chiaroscuro Rd.	Portland	OR	10073	USA	(503) 555-0117	(503) 555-0129
55	Customer KZQZT	Wood, Robin	    Sales Representative	7890 Bering St.	Anchorage	AK	10050	USA	(907) 555-0115	(907) 555-0128
65	Customer NYUHS	Moore, Michael	Assistant Sales Representative	6789 Milton Dr.	Albuquerque	NM	10109	USA	(505) 555-0125	(505) 555-0134
71	Customer LCOUJ	Navarro, TomÃ¡s	Sales Representative	9012 Suffolk Ln.	Boise	ID	10078	USA	(208) 555-0116	NULL
75	Customer XOJYP	Downs, Chris	Sales Manager	P.O. Box 1234	Lander	WY	10113	USA	(307) 555-0114	(307) 555-0127
77	Customer LCYBZ	Didcock, Cliff	Marketing Manager	2345 Jefferson Way Suite 2	Portland	OR	10042	USA	(503) 555-0120	NULL
78	Customer NLTYP	Ma, Andrew	    Marketing Assistant	0123 Grizzly Peak Rd.	Butte	MT	10107	USA	(406) 555-0121	(406) 555-0131
82	Customer EYHKM	Veninga, Tjeerd	Sales Associate	1234 DaVinci Blvd.	Kirkland	WA	10119	USA	(206) 555-0124	(206) 555-0133
89	Customer YBQTI	Smith Jr., Ronaldo	Owner	8901 - 14th Ave. S. Suite 3B	Seattle	WA	10049	USA	(206) 555-0123	(206) 555-0132

In [ ]:
--Use TSQLV4
--SELECT custid, companyname, contactname, contacttitle, address, city, region, postalcode, country, phone, fax
--FROM Sales.Customers
--WHERE country = N'USA'
--WITH CHECK OPTION;

USE Northwinds2022TSQLV7
SELECT CustomerId, CustomerCompanyName, CustomerContactName, CustomerContactTitle, CustomerAddress, CustomerCity, CustomerRegion, CustomerPostalCode, CustomerCountry, CustomerPhoneNumber, CustomerFaxNumber
FROM Sales.Customer
WHERE CustomerCountry = N'USA'


EXPLANATION
the script given in the question is modifying a table view named Sales.USACusts. this view is designed to select columns from Sales.Customers table but only where country is USA. at the end the query does a clean up oeration. it deletes all customers with custid greater than 91 and to remove the test data.  GO statements are used to separate the script into batches for execution.

Chapter 5 QUestion 8


-- Instead, use ORDER BY in Outer Query SELECT custid, companyname, region FROM Sales.USACusts ORDER BY region; GO

-- Do not Rely on TOP ALTER VIEW Sales.USACusts AS

SELECT TOP (100) PERCENT custid, companyname, contactname, contacttitle, address, city, region, postalcode, country, phone, fax FROM Sales.Customers WHERE country = N'USA' ORDER BY region; GO


Proposition
--select all USA-based customer details from Sales.Customers, ordered by region, using TOP (100) PERCENT to imply full dataset retrieval.


Expected Output

custid	companyname	contactname	contacttitle	address	city	region	postalcode	country	phone	fax
55	Customer KZQZT	Wood, Robin	Sales Representative	7890 Bering St.	Anchorage	AK	10050	USA	(907) 555-0115	(907) 555-0128
45	Customer QXPPT	Wright, David	Owner	1234 Polk St. Suite 5	San Francisco	CA	10062	USA	(415) 555-0118	NULL
71	Customer LCOUJ	Navarro, TomÃ¡s	Sales Representative	9012 Suffolk Ln.	Boise	ID	10078	USA	(208) 555-0116	NULL
78	Customer NLTYP	Ma, Andrew	Marketing Assistant	0123 Grizzly Peak Rd.	Butte	MT	10107	USA	(406) 555-0121	(406) 555-0131
65	Customer NYUHS	Moore, Michael	Assistant Sales Representative	6789 Milton Dr.	Albuquerque	NM	10109	USA	(505) 555-0125	(505) 555-0134
48	Customer DVFMB	Szymczak, RadosÅaw	Sales Manager	9012 Chiaroscuro Rd.	Portland	OR	10073	USA	(503) 555-0117	(503) 555-0129
32	Customer YSIQX	Krishnan, Venky	Marketing Manager	6789 Baker Blvd.	Eugene	OR	10070	USA	(503) 555-0122	NULL
36	Customer LVJSO	Smith, Denise	Sales Representative	City Center Plaza 2345 Main St.	Elgin	OR	10103	USA	(503) 555-0126	(503) 555-0135
77	Customer LCYBZ	Didcock, Cliff	Marketing Manager	2345 Jefferson Way Suite 2	Portland	OR	10042	USA	(503) 555-0120	NULL
82	Customer EYHKM	Veninga, Tjeerd	Sales Associate	1234 DaVinci Blvd.	Kirkland	WA	10119	USA	(206) 555-0124	(206) 555-0133
89	Customer YBQTI	Smith Jr., Ronaldo	Owner	8901 - 14th Ave. S. Suite 3B	Seattle	WA	10049	USA	(206) 555-0123	(206) 555-0132
43	Customer UISOJ	Wu, Qiong	Marketing Manager	8901 Orchestra Terrace	Walla Walla	WA	10069	USA	(509) 555-0119	(509) 555-0130
75	Customer XOJYP	Downs, Chris	Sales Manager	P.O. Box 1234	Lander	WY	10113	USA	(307) 555-0114	(307) 555-0127

In [ ]:

--USE TSQLV4
--SELECT TOP (100) PERCENT custid, companyname, contactname, contacttitle, address, city, region, postalcode, country, phone, fax
--FROM Sales.Customers
--WHERE country = N'USA'
--ORDER BY region;


USE Northwinds2022TSQLV7
SELECT TOP (100) PERCENT CustomerId, CustomerCompanyName, CustomerContactName, CustomerContactTitle, CustomerAddress, customercity, customerregion, customerpostalcode, customercountry, CustomerPhoneNumber, CustomerFaxNumber
FROM Sales.Customer
WHERE CustomerCountry = N'USA'
ORDER BY CustomerRegion;

Explanation

the first part is very simple. retrieve all the column names from the table. uses a where clause to indicate countries where the value will be USA. the second part modifies the view to select top 100 percent of rows from sales.cunstomers table. then attempt to order it at the end by the region column. Top 100 is really not effective is enfrocing a order. the previous query focused on WITH CHECK OPTION for data integrity and cleanup. THis query uses the best method to order data when working with view.

Chapter 5 Question 9


Q9:
-- External column aliasing WITH C(orderyear, custid) AS ( SELECT YEAR(orderdate), custid FROM Sales.Orders ) SELECT orderyear, COUNT(DISTINCT custid) AS numcusts FROM C GROUP BY orderyear; GO


Proposition
--Calculate the number of unique customers who placed orders in each year from the Sales.[Order] table in the Northwinds2022TSQLV7 database.
--Utilizes a Common Table Expression (CTE) named C with columns orderyear and custid to organize the data before counting distinct customers per year.



Expected Output
orderyear	numcusts
2014	67
2015	86
2016	81

In [ ]:
--code
--USE TSQLV4;
--GO

--WITH C(orderyear, custid) AS (
--  SELECT YEAR(orderdate) AS orderyear, custid
--  FROM Sales.Orders
--)
--SELECT orderyear, COUNT(DISTINCT custid) AS numcusts
--FROM C
--GROUP BY orderyear;
--GO


USE Northwinds2022TSQLV7;
GO

;WITH C(orderyear, custid) AS (
  SELECT YEAR(orderdate) AS orderyear, CustomerId
  FROM Sales.[Order]
)
SELECT orderyear, COUNT(DISTINCT custid) AS numcusts
FROM C
GROUP BY orderyear;
GO

explanation
this query uses a common table expression. it calculates the year from the orderdate field and customer ID selected directly. this step tranforms the fields into a more digestable form. after that the main query selects it and prepares a simplifed table that groups orders bt the year they were made and the customers associated with those orders.

Chapter 5 Question 10




Q10
DECLARE @empid AS INT = 3;

SELECT orderyear, COUNT(DISTINCT custid) AS numcusts FROM (SELECT YEAR(orderdate) AS orderyear, custid FROM Sales.Orders WHERE empid = @empid) AS D GROUP BY orderyear; GO ```


Proposition 
--Filter orders by a specific employee (ID 3) from the Sales.Orders table and calculates the number of unique customers per year who placed orders handled by that employee.
--Utilize a subquery named D to organize order data by year (orderyear) and customer ID (custid) before performing the distinct customer count per year.



Expected outpuut

orderyear	numcusts
2014	16
2015	46
2016	30

In [ ]:
--code

--use TSQLV4
--DECLARE @empid AS INT = 3;

--SELECT orderyear, COUNT(DISTINCT custid) AS numcusts 
--FROM (
--    SELECT YEAR(orderdate) AS orderyear, custid 
--    FROM Sales.Orders 
--    WHERE empid = @empid
--) AS D 
--GROUP BY orderyear;
--GO

use Northwinds2022TSQLV7
DECLARE @empid AS INT = 3;

SELECT orderyear, COUNT(DISTINCT CustomerId) AS numcusts 
FROM (
    SELECT YEAR(orderdate) AS orderyear, CustomerId 
    FROM Sales.[Order] 
    WHERE EmployeeId = @empid
) AS D 
GROUP BY orderyear;
GO

explanation
first we delcare the variable empid to 3. then the subquery is used to filter the sales.order table to show only the orders with the empid of 3. the outerquery takes the output of the inner query and then groups the data by orderyear. this can show a specific emplpoyees customer engagement.